/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/get-started`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/../pages/add-modal/_components/place-search-bar/place-search-bar.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../pages/add-modal/_components/place-search-bar/place-search-bar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/add-modal` | `/add-modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/entry-form` | `/entry-form`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/get-started`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/../pages/add-modal/_components/place-search-bar/place-search-bar.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../pages/add-modal/_components/place-search-bar/place-search-bar`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/add-modal` | `/add-modal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/entry-form` | `/entry-form`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/get-started${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/../pages/add-modal/_components/place-search-bar/place-search-bar.styles${`?${string}` | `#${string}` | ''}` | `/../pages/add-modal/_components/place-search-bar/place-search-bar${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/add-modal${`?${string}` | `#${string}` | ''}` | `/add-modal${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/entry-form${`?${string}` | `#${string}` | ''}` | `/entry-form${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/get-started`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/../pages/add-modal/_components/place-search-bar/place-search-bar.styles`; params?: Router.UnknownInputParams; } | { pathname: `/../pages/add-modal/_components/place-search-bar/place-search-bar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/add-modal` | `/add-modal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/entry-form` | `/entry-form`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
